name: pbkdf2_dart
version: 2.1.0
author: James Ots <code@jamesots.com>
homepage: https://github.com/marceloneppel/pbkdf2
description: Implementation of PBKDF2 key derivation function
environment:
  # Works in Dart 1 (starting with 1.20.1), and works in Dart 2.
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  crypto: ^3.0.1
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.3
